### PR TITLE
Fix blitz custom server

### PR DESCRIPTION
**Pull request by flybayer**
Currently blitz ignores any files ignored by git. This is clearly not good in this case. We'll get this fixed, but for now this works.

### CODE REVIEW

**Comment by ericvicenti** [comment]
Thanks! I tested this and unfortunately there were other issues. TSC was frustrating me because of failing type checks, so I switched to esbuild, which is also much faster.

I pushed the following build commands to the main branch:
```
    "dev": "yarn build:server && blitz dev",
    "build": "yarn build:server && blitz build",
    "build:server": "esbuild server.ts --outdir=. --format=cjs",
```

The custom server is being used now! 

Here is the latest error for both dev and prod:  

```
Error: Cannot find module './db'
Require stack:
- /PATH/cobase/.blitz/build/server.js
```

This makes sense because db is built separately by webpack. How can the `server.ts` access the db and the rest of the application?

**Comment by flybayer** [comment]
@ericvicenti solution is to also build `db/index.ts -> db/index.js` with esbuild

**Comment by ericvicenti** [comment]
Sure, I tried that and pushed results to main.

```
    "build:server": "esbuild server.ts db/index.ts --outdir=./ --platform=node --target=node15 --format=cjs",
```

Good news, this now works for the `yarn build` and `yarn start` workflow!

Bad news1: this still causes a strange error while running `yarn dev`:

```
error - ../../node_modules/cross-spawn/index.js:3:0
Module not found: Can't resolve 'child_process'
```

Then when I try to load a page, the following error occurs (in dev mode):

```
Error: Cannot find module 'PATH/cobase/.blitz/build/.next/build-manifest.json'
```

Bad news 2: now there will be a duplicate js file checked in for every ts file that is used on the server-side? This seems painful.

Given all of this struggle, I am considering separate "front end" and "back end" services, until Blitz adds full support for TS on the server-side.

**Comment by flybayer** [comment]
Here's the solution to both child_process and build-manifest errors. Blitz will automatically load the config
```diff
// server.ts
-const app = blitz({ dev, conf: require("./blitz.config.js") })
+const app = blitz({ dev })
```

> Bad news 2: now there will be a duplicate js file checked in for every ts file that is used on the server-side? This seems painful.

Yes, but not every file that is "server-side", only files used in your custom server. It’s absolutely painful — fixing this is currently blocked by the next.js fork integration which I'm working on as fast as I can.

**Comment by ericvicenti** [comment]
Ah, thanks! I have no idea how the custom server file works in dev and prod mode, so I was using some wrong assumptions!

This solution works for now. I put together a custom plugin for esbuild, so it bundles all the server code into server.js, without including dependencies.

```
    "dev": "yarn build:server && blitz dev",
    "build": "yarn build:server && blitz build",
    "build:server": "node server-build.js",
```

https://github.com/co-base/co.base/blob/be76dad44c4ae07135196c286e858e8a1247dc64/server-build.js

Thanks for taking your time to help! Good luck on the next.js integration!

**Comment by flybayer** [comment]
Awesome!
